// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { CodecTypes as PgTypes } from '@prisma/orm-postgres/target/codec-types';
import type { QueryOperationTypes as PgTargetQueryOps } from '@prisma/orm-postgres/target/operation-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'59f8a4e2f26fe0889340122c641740662eeb4c32bdd59db77d4115eeffce50e4'>;
export type ExecutionHash =
  ExecutionHashBase<'f6abaa8ded6388f07cf526305d7260d3fd992dafef4e43d0473400e8d5926be6'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgTargetQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly File: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly dedupOfId: CodecTypes['pg/text@1']['output'] | null;
      readonly expiresAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly mime: CodecTypes['pg/text@1']['output'] | null;
      readonly originalName: CodecTypes['pg/text@1']['output'];
      readonly ownerId: CodecTypes['pg/text@1']['output'];
      readonly scanResult: CodecTypes['pg/text@1']['output'] | null;
      readonly sha256: CodecTypes['pg/text@1']['output'] | null;
      readonly sizeBytes: CodecTypes['pg/int8@1']['output'];
      readonly status:
        | 'uploading'
        | 'uploaded'
        | 'scanning'
        | 'ready'
        | 'infected'
        | 'scan_failed'
        | 'expired'
        | 'deleted';
      readonly storageKey: CodecTypes['pg/text@1']['output'];
    };
    readonly IdempotencyKey: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly key: CodecTypes['pg/text@1']['output'];
      readonly requestHash: CodecTypes['pg/text@1']['output'] | null;
      readonly response: CodecTypes['pg/json@1']['output'] | null;
      readonly route: CodecTypes['pg/text@1']['output'];
      readonly statusCode: CodecTypes['pg/int4@1']['output'] | null;
      readonly userId: CodecTypes['pg/text@1']['output'];
    };
    readonly Job: {
      readonly attempts: CodecTypes['pg/int4@1']['output'];
      readonly fileId: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int8@1']['output'];
      readonly lockedAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly runAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly status: CodecTypes['pg/text@1']['output'];
      readonly type: CodecTypes['pg/text@1']['output'];
    };
    readonly ShareLink: {
      readonly downloadCount: CodecTypes['pg/int4@1']['output'];
      readonly expiresAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly fileId: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly maxDownloads: CodecTypes['pg/int4@1']['output'] | null;
      readonly passwordHash: CodecTypes['pg/text@1']['output'] | null;
      readonly slug: CodecTypes['pg/text@1']['output'];
    };
    readonly UploadSession: {
      readonly expiresAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly fileId: CodecTypes['pg/text@1']['output'];
      readonly fingerprint: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly partSize: CodecTypes['pg/int4@1']['output'];
      readonly r2UploadId: CodecTypes['pg/text@1']['output'];
      readonly totalParts: CodecTypes['pg/int4@1']['output'];
    };
    readonly User: {
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly passwordHash: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly File: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly dedupOfId: CodecTypes['pg/text@1']['input'] | null;
      readonly expiresAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly mime: CodecTypes['pg/text@1']['input'] | null;
      readonly originalName: CodecTypes['pg/text@1']['input'];
      readonly ownerId: CodecTypes['pg/text@1']['input'];
      readonly scanResult: CodecTypes['pg/text@1']['input'] | null;
      readonly sha256: CodecTypes['pg/text@1']['input'] | null;
      readonly sizeBytes: CodecTypes['pg/int8@1']['input'];
      readonly status:
        | 'uploading'
        | 'uploaded'
        | 'scanning'
        | 'ready'
        | 'infected'
        | 'scan_failed'
        | 'expired'
        | 'deleted';
      readonly storageKey: CodecTypes['pg/text@1']['input'];
    };
    readonly IdempotencyKey: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly key: CodecTypes['pg/text@1']['input'];
      readonly requestHash: CodecTypes['pg/text@1']['input'] | null;
      readonly response: CodecTypes['pg/json@1']['input'] | null;
      readonly route: CodecTypes['pg/text@1']['input'];
      readonly statusCode: CodecTypes['pg/int4@1']['input'] | null;
      readonly userId: CodecTypes['pg/text@1']['input'];
    };
    readonly Job: {
      readonly attempts: CodecTypes['pg/int4@1']['input'];
      readonly fileId: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int8@1']['input'];
      readonly lockedAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly runAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly status: CodecTypes['pg/text@1']['input'];
      readonly type: CodecTypes['pg/text@1']['input'];
    };
    readonly ShareLink: {
      readonly downloadCount: CodecTypes['pg/int4@1']['input'];
      readonly expiresAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly fileId: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly maxDownloads: CodecTypes['pg/int4@1']['input'] | null;
      readonly passwordHash: CodecTypes['pg/text@1']['input'] | null;
      readonly slug: CodecTypes['pg/text@1']['input'];
    };
    readonly UploadSession: {
      readonly expiresAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly fileId: CodecTypes['pg/text@1']['input'];
      readonly fingerprint: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly partSize: CodecTypes['pg/int4@1']['input'];
      readonly r2UploadId: CodecTypes['pg/text@1']['input'];
      readonly totalParts: CodecTypes['pg/int4@1']['input'];
    };
    readonly User: {
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly passwordHash: CodecTypes['pg/text@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly File: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly dedupOfId: CodecTypes['pg/text@1']['output'] | null;
      readonly expiresAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly mime: CodecTypes['pg/text@1']['output'] | null;
      readonly originalName: CodecTypes['pg/text@1']['output'];
      readonly ownerId: CodecTypes['pg/text@1']['output'];
      readonly scanResult: CodecTypes['pg/text@1']['output'] | null;
      readonly sha256: CodecTypes['pg/text@1']['output'] | null;
      readonly sizeBytes: CodecTypes['pg/int8@1']['output'];
      readonly status:
        | 'uploading'
        | 'uploaded'
        | 'scanning'
        | 'ready'
        | 'infected'
        | 'scan_failed'
        | 'expired'
        | 'deleted';
      readonly storageKey: CodecTypes['pg/text@1']['output'];
    };
    readonly IdempotencyKey: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly key: CodecTypes['pg/text@1']['output'];
      readonly requestHash: CodecTypes['pg/text@1']['output'] | null;
      readonly response: CodecTypes['pg/json@1']['output'] | null;
      readonly route: CodecTypes['pg/text@1']['output'];
      readonly statusCode: CodecTypes['pg/int4@1']['output'] | null;
      readonly userId: CodecTypes['pg/text@1']['output'];
    };
    readonly Job: {
      readonly attempts: CodecTypes['pg/int4@1']['output'];
      readonly fileId: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int8@1']['output'];
      readonly lockedAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly runAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly status: CodecTypes['pg/text@1']['output'];
      readonly type: CodecTypes['pg/text@1']['output'];
    };
    readonly ShareLink: {
      readonly downloadCount: CodecTypes['pg/int4@1']['output'];
      readonly expiresAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly fileId: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly maxDownloads: CodecTypes['pg/int4@1']['output'] | null;
      readonly passwordHash: CodecTypes['pg/text@1']['output'] | null;
      readonly slug: CodecTypes['pg/text@1']['output'];
    };
    readonly UploadSession: {
      readonly expiresAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly fileId: CodecTypes['pg/text@1']['output'];
      readonly fingerprint: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly partSize: CodecTypes['pg/int4@1']['output'];
      readonly r2UploadId: CodecTypes['pg/text@1']['output'];
      readonly totalParts: CodecTypes['pg/int4@1']['output'];
    };
    readonly User: {
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly passwordHash: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly File: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly dedupOfId: CodecTypes['pg/text@1']['input'] | null;
      readonly expiresAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly mime: CodecTypes['pg/text@1']['input'] | null;
      readonly originalName: CodecTypes['pg/text@1']['input'];
      readonly ownerId: CodecTypes['pg/text@1']['input'];
      readonly scanResult: CodecTypes['pg/text@1']['input'] | null;
      readonly sha256: CodecTypes['pg/text@1']['input'] | null;
      readonly sizeBytes: CodecTypes['pg/int8@1']['input'];
      readonly status:
        | 'uploading'
        | 'uploaded'
        | 'scanning'
        | 'ready'
        | 'infected'
        | 'scan_failed'
        | 'expired'
        | 'deleted';
      readonly storageKey: CodecTypes['pg/text@1']['input'];
    };
    readonly IdempotencyKey: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly key: CodecTypes['pg/text@1']['input'];
      readonly requestHash: CodecTypes['pg/text@1']['input'] | null;
      readonly response: CodecTypes['pg/json@1']['input'] | null;
      readonly route: CodecTypes['pg/text@1']['input'];
      readonly statusCode: CodecTypes['pg/int4@1']['input'] | null;
      readonly userId: CodecTypes['pg/text@1']['input'];
    };
    readonly Job: {
      readonly attempts: CodecTypes['pg/int4@1']['input'];
      readonly fileId: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int8@1']['input'];
      readonly lockedAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly runAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly status: CodecTypes['pg/text@1']['input'];
      readonly type: CodecTypes['pg/text@1']['input'];
    };
    readonly ShareLink: {
      readonly downloadCount: CodecTypes['pg/int4@1']['input'];
      readonly expiresAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly fileId: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly maxDownloads: CodecTypes['pg/int4@1']['input'] | null;
      readonly passwordHash: CodecTypes['pg/text@1']['input'] | null;
      readonly slug: CodecTypes['pg/text@1']['input'];
    };
    readonly UploadSession: {
      readonly expiresAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly fileId: CodecTypes['pg/text@1']['input'];
      readonly fingerprint: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly partSize: CodecTypes['pg/int4@1']['input'];
      readonly r2UploadId: CodecTypes['pg/text@1']['input'];
      readonly totalParts: CodecTypes['pg/int4@1']['input'];
    };
    readonly User: {
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly passwordHash: CodecTypes['pg/text@1']['input'];
    };
  };
};

export namespace Models {
  export type public_File = {
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    dedupOfId: CodecTypes['pg/text@1']['output'] | null;
    expiresAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    mime: CodecTypes['pg/text@1']['output'] | null;
    originalName: CodecTypes['pg/text@1']['output'];
    ownerId: CodecTypes['pg/text@1']['output'];
    scanResult: CodecTypes['pg/text@1']['output'] | null;
    sha256: CodecTypes['pg/text@1']['output'] | null;
    sizeBytes: CodecTypes['pg/int8@1']['output'];
    status:
      | 'uploading'
      | 'uploaded'
      | 'scanning'
      | 'ready'
      | 'infected'
      | 'scan_failed'
      | 'expired'
      | 'deleted';
    storageKey: CodecTypes['pg/text@1']['output'];
    dedupOf: public_File | null;
    duplicates: public_File[];
    owner: public_User;
    session: public_UploadSession | null;
    shareLinks: public_ShareLink[];
    readonly [RelationKeys]?: 'dedupOf' | 'duplicates' | 'owner' | 'session' | 'shareLinks';
  };
  export type public_IdempotencyKey = {
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    key: CodecTypes['pg/text@1']['output'];
    requestHash: CodecTypes['pg/text@1']['output'] | null;
    response: CodecTypes['pg/json@1']['output'] | null;
    route: CodecTypes['pg/text@1']['output'];
    statusCode: CodecTypes['pg/int4@1']['output'] | null;
    userId: CodecTypes['pg/text@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type public_Job = {
    attempts: CodecTypes['pg/int4@1']['output'];
    fileId: CodecTypes['pg/text@1']['output'];
    id: CodecTypes['pg/int8@1']['output'];
    lockedAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    runAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    status: CodecTypes['pg/text@1']['output'];
    type: CodecTypes['pg/text@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type public_ShareLink = {
    downloadCount: CodecTypes['pg/int4@1']['output'];
    expiresAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    fileId: CodecTypes['pg/text@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    maxDownloads: CodecTypes['pg/int4@1']['output'] | null;
    passwordHash: CodecTypes['pg/text@1']['output'] | null;
    slug: CodecTypes['pg/text@1']['output'];
    file: public_File;
    readonly [RelationKeys]?: 'file';
  };
  export type public_UploadSession = {
    expiresAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    fileId: CodecTypes['pg/text@1']['output'];
    fingerprint: CodecTypes['pg/text@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    partSize: CodecTypes['pg/int4@1']['output'];
    r2UploadId: CodecTypes['pg/text@1']['output'];
    totalParts: CodecTypes['pg/int4@1']['output'];
    file: public_File;
    readonly [RelationKeys]?: 'file';
  };
  export type public_User = {
    email: CodecTypes['pg/text@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    passwordHash: CodecTypes['pg/text@1']['output'];
    files: public_File[];
    readonly [RelationKeys]?: 'files';
  };
}

export declare const models: {
  public: {
    File: Models.public_File;
    IdempotencyKey: Models.public_IdempotencyKey;
    Job: Models.public_Job;
    ShareLink: Models.public_ShareLink;
    UploadSession: Models.public_UploadSession;
    User: Models.public_User;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly File: {
              columns: {
                readonly createdAt: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly many: false;
                };
                readonly dedupOfId: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly expiresAt: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly id: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly mime: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly originalName: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly ownerId: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly scanResult: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly sha256: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly sizeBytes: {
                  readonly dataType: 'pg/int8';
                  readonly codecId: 'pg/int8@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly status: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'uploading'>;
                  };
                  readonly many: false;
                };
                readonly storageKey: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['storageKey'] }];
              indexes: readonly [
                {
                  readonly name: 'File_dedupOfId_idx_f7581ae4';
                  readonly prefix: 'File_dedupOfId_idx';
                  readonly columns: readonly ['dedupOfId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'File_ownerId_idx_e2d0c1ef';
                  readonly prefix: 'File_ownerId_idx';
                  readonly columns: readonly ['ownerId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'File';
                    readonly columns: readonly ['ownerId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'User';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'File';
                    readonly columns: readonly ['dedupOfId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'File';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly IdempotencyKey: {
              columns: {
                readonly createdAt: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly many: false;
                };
                readonly key: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly requestHash: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly response: {
                  readonly dataType: 'pg/json';
                  readonly codecId: 'pg/json@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly route: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly statusCode: {
                  readonly dataType: 'pg/int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly userId: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
              };
              primaryKey: { readonly columns: readonly ['userId', 'key', 'route'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly Job: {
              columns: {
                readonly attempts: {
                  readonly dataType: 'pg/int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                  readonly many: false;
                };
                readonly fileId: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly id: {
                  readonly dataType: 'pg/int8';
                  readonly codecId: 'pg/int8@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                  readonly many: false;
                };
                readonly lockedAt: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly runAt: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly many: false;
                };
                readonly status: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'queued'>;
                  };
                  readonly many: false;
                };
                readonly type: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly ShareLink: {
              columns: {
                readonly downloadCount: {
                  readonly dataType: 'pg/int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                  readonly many: false;
                };
                readonly expiresAt: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly fileId: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly id: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly maxDownloads: {
                  readonly dataType: 'pg/int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly passwordHash: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly slug: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['slug'] }];
              indexes: readonly [
                {
                  readonly name: 'ShareLink_fileId_idx_9a9e456b';
                  readonly prefix: 'ShareLink_fileId_idx';
                  readonly columns: readonly ['fileId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'ShareLink';
                    readonly columns: readonly ['fileId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'File';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly UploadSession: {
              columns: {
                readonly expiresAt: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly fileId: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly fingerprint: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly id: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly partSize: {
                  readonly dataType: 'pg/int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly r2UploadId: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly totalParts: {
                  readonly dataType: 'pg/int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly many: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['fileId'] }];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'UploadSession';
                    readonly columns: readonly ['fileId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'File';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly User: {
              columns: {
                readonly email: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly id: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly passwordHash: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['email'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly FileStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'uploading',
                'uploaded',
                'scanning',
                'ready',
                'infected',
                'scan_failed',
                'expired',
                'deleted',
              ];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly File: { readonly namespace: 'public' & NamespaceId; readonly model: 'File' };
    readonly IdempotencyKey: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'IdempotencyKey';
    };
    readonly Job: { readonly namespace: 'public' & NamespaceId; readonly model: 'Job' };
    readonly ShareLink: { readonly namespace: 'public' & NamespaceId; readonly model: 'ShareLink' };
    readonly UploadSession: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'UploadSession';
    };
    readonly User: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly File: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly dedupOfId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly expiresAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly mime: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly originalName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly ownerId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly scanResult: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly sha256: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly sizeBytes: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly storageKey: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly dedupOf: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'File' };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['dedupOfId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly duplicates: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'File' };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['dedupOfId'];
                };
              };
              readonly owner: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['ownerId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly session: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'UploadSession';
                };
                readonly cardinality: '1:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['fileId'];
                };
              };
              readonly shareLinks: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ShareLink';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['fileId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'File';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly createdAt: { readonly column: 'createdAt' };
                readonly dedupOfId: { readonly column: 'dedupOfId' };
                readonly expiresAt: { readonly column: 'expiresAt' };
                readonly id: { readonly column: 'id' };
                readonly mime: { readonly column: 'mime' };
                readonly originalName: { readonly column: 'originalName' };
                readonly ownerId: { readonly column: 'ownerId' };
                readonly scanResult: { readonly column: 'scanResult' };
                readonly sha256: { readonly column: 'sha256' };
                readonly sizeBytes: { readonly column: 'sizeBytes' };
                readonly status: { readonly column: 'status' };
                readonly storageKey: { readonly column: 'storageKey' };
              };
            };
          };
          readonly IdempotencyKey: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly key: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly requestHash: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly response: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/json@1' };
              };
              readonly route: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly statusCode: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'IdempotencyKey';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly createdAt: { readonly column: 'createdAt' };
                readonly key: { readonly column: 'key' };
                readonly requestHash: { readonly column: 'requestHash' };
                readonly response: { readonly column: 'response' };
                readonly route: { readonly column: 'route' };
                readonly statusCode: { readonly column: 'statusCode' };
                readonly userId: { readonly column: 'userId' };
              };
            };
          };
          readonly Job: {
            readonly fields: {
              readonly attempts: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly fileId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8@1' };
              };
              readonly lockedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly runAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly type: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'Job';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly attempts: { readonly column: 'attempts' };
                readonly fileId: { readonly column: 'fileId' };
                readonly id: { readonly column: 'id' };
                readonly lockedAt: { readonly column: 'lockedAt' };
                readonly runAt: { readonly column: 'runAt' };
                readonly status: { readonly column: 'status' };
                readonly type: { readonly column: 'type' };
              };
            };
          };
          readonly ShareLink: {
            readonly fields: {
              readonly downloadCount: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly expiresAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly fileId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly maxDownloads: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly passwordHash: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly slug: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly file: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'File' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['fileId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'ShareLink';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly downloadCount: { readonly column: 'downloadCount' };
                readonly expiresAt: { readonly column: 'expiresAt' };
                readonly fileId: { readonly column: 'fileId' };
                readonly id: { readonly column: 'id' };
                readonly maxDownloads: { readonly column: 'maxDownloads' };
                readonly passwordHash: { readonly column: 'passwordHash' };
                readonly slug: { readonly column: 'slug' };
              };
            };
          };
          readonly UploadSession: {
            readonly fields: {
              readonly expiresAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly fileId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly fingerprint: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly partSize: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly r2UploadId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly totalParts: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly file: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'File' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['fileId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'UploadSession';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly expiresAt: { readonly column: 'expiresAt' };
                readonly fileId: { readonly column: 'fileId' };
                readonly fingerprint: { readonly column: 'fingerprint' };
                readonly id: { readonly column: 'id' };
                readonly partSize: { readonly column: 'partSize' };
                readonly r2UploadId: { readonly column: 'r2UploadId' };
                readonly totalParts: { readonly column: 'totalParts' };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly passwordHash: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly files: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'File' };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['ownerId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'User';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly email: { readonly column: 'email' };
                readonly id: { readonly column: 'id' };
                readonly passwordHash: { readonly column: 'passwordHash' };
              };
            };
          };
        };
        readonly enum: {
          readonly FileStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'uploading'; readonly value: 'uploading' },
              { readonly name: 'uploaded'; readonly value: 'uploaded' },
              { readonly name: 'scanning'; readonly value: 'scanning' },
              { readonly name: 'ready'; readonly value: 'ready' },
              { readonly name: 'infected'; readonly value: 'infected' },
              { readonly name: 'scan_failed'; readonly value: 'scan_failed' },
              { readonly name: 'expired'; readonly value: 'expired' },
              { readonly name: 'deleted'; readonly value: 'deleted' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly forKeyShare: true;
      readonly forNoKeyUpdate: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly forShare: true;
      readonly forUpdate: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly lateral: true;
      readonly lockNowait: true;
      readonly lockOf: true;
      readonly lockSkipLocked: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'File';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'ShareLink';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'UploadSession';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'User';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
